"""The appendix's numbers as LaTeX macros, from the measurement files.

paper/README.md: nothing numeric in main.tex is typed. The appendix is no
exception, so its numbers are emitted here and \\input by main.tex. The
reportlab build reads the same JSONs directly and does not need this.
"""
import json
from pathlib import Path

R = Path(__file__).resolve().parent / "results"
G = json.loads((R / "per_frame_guarantee.json").read_text())
S = json.loads((R / "safe_routing.json").read_text())
og, op = G["modes"]["global"], G["modes"]["perframe"]
pg, sg = S["rows"][0], S["signalled_lambda_perframe"]
thr = min(S["decoder_perframe"], key=lambda r: r["max"])
mg = max(S["rows"], key=lambda r: r["saving_pct"])

M = {
    "GuardN": f"{og['n']}",
    "GuardOverN": f"{og['over_budget']}",
    "GuardPNinetyFive": f"{og['p95']:.3f}",
    "GuardMax": f"{og['max']:.3f}",
    "GuardSaving": f"{og['saving_pct']:.2f}",
    "GuardPfIn": f"{op['n'] - op['over_budget']}",
    "GuardPfMax": f"{op['max']:.3f}",
    "GuardPfSaving": f"{op['saving_pct']:.2f}",
    "GuardDecMax": f"{pg['max']:.3f}",
    "GuardDecSaving": f"{pg['saving_pct']:.2f}",
    "GuardMarginMax": f"{mg['max']:.3f}",
    "GuardThrMax": f"{thr['max']:.3f}",
    "GuardThrSaving": f"{thr['saving_pct']:.2f}",
    "GuardSigIn": f"{sg['n'] - sg['over_010']}",
    "GuardSigMax": f"{sg['max']:.3f}",
    "GuardSigSaving": f"{sg['saving_pct']:.2f}",
}
out = Path.home() / "FLEX-UF/paper/tables/macros_appendix.tex"
out.write_text("% generated by flexplus/emit_appendix_macros.py -- do not edit\n"
               + "".join(f"\\newcommand{{\\{k}}}{{{v}}}\n" for k, v in M.items()))
print(f"  {len(M)} makro -> {out}")
for k, v in M.items():
    print(f"    \\{k} = {v}")
