"""Clean image assets for a hand-drawn patchify diagram.

Writes into paper_figures/ -- not docs/figures, because these are not figures
this repository generates for the paper. They are raw material: a frame, the
same frame with the tile lattice on it, and three tiles cut out of it, to be
arranged by hand.

No axes, no titles, no padding. Just pixels.

    python scripts/make_patch_assets.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import torch
import torch.nn.functional as F
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(Path.home() / "DCVC"))

import ctc_intra as C  # noqa: E402
from src.utils.transforms import ycbcr2rgb  # noqa: E402

OUT = ROOT / "paper_figures"
SEQ = "Bosphorus"
P = 256                      # the shipped tile side, in RGB pixels

# Three tiles chosen to be visibly different kinds of content, because the point
# of the diagram is that a tile's difficulty is a property of what is in it:
# dense texture, a hard object, and near-flat water.
# (row, col) on the padded lattice, and a name that says why.
PICKS = [((0, 1), "hillside"), ((2, 3), "boat"), ((3, 6), "water")]


def to_rgb8(t: torch.Tensor) -> np.ndarray:
    """Decoder tensors are YCbCr 4:4:4 shifted by -0.5, not RGB."""
    rgb = ycbcr2rgb(t + 0.5)
    a = np.clip(rgb[0].permute(1, 2, 0).cpu().numpy(), 0, 1)
    return (a * 255 + 0.5).astype(np.uint8)


def main() -> int:
    OUT.mkdir(exist_ok=True)
    seqs, _ = C.discover([])
    s = next((q for q in seqs if q["name"].startswith(SEQ)), None)
    if s is None:
        print(f"{SEQ} not found in the CTC set")
        return 1
    x, _ = C.read_frames(s["path"], s["w"], s["h"], 1, 1)
    x = x[:1]
    _, _, H, W = x.shape

    # The decoder pads up to a whole number of tiles before doing anything, so
    # the lattice is drawn on the padded frame, not the 1920x1080 one.
    ph, pw = (-H) % P, (-W) % P
    xp = F.pad(x, (0, pw, 0, ph), mode="replicate") if (ph or pw) else x
    img = Image.fromarray(to_rgb8(xp))
    nh, nw = img.height // P, img.width // P

    img.save(OUT / "frame_full.png")
    print(f"  frame_full.png            {img.width}x{img.height}")

    # the same frame with the lattice on it
    grid = img.copy()
    d = ImageDraw.Draw(grid)
    for i in range(1, nw):
        d.line([(i * P, 0), (i * P, grid.height)], fill=(255, 255, 255), width=3)
    for j in range(1, nh):
        d.line([(0, j * P), (grid.width, j * P)], fill=(255, 255, 255), width=3)
    grid.save(OUT / "frame_grid.png")
    print(f"  frame_grid.png            {nh}x{nw} tiles of {P}px")

    # the same again, with the three picked tiles outlined
    marked = grid.copy()
    dm = ImageDraw.Draw(marked)
    for (r, c), _name in PICKS:
        dm.rectangle([c * P, r * P, (c + 1) * P - 1, (r + 1) * P - 1],
                     outline=(255, 92, 0), width=9)
    marked.save(OUT / "frame_grid_marked.png")
    print(f"  frame_grid_marked.png     {len(PICKS)} tiles outlined")

    for k, ((r, c), name) in enumerate(PICKS, 1):
        tile = img.crop((c * P, r * P, (c + 1) * P, (r + 1) * P))
        tile.save(OUT / f"patch_{k}_{name}.png")
        print(f"  patch_{k}_{name}.png{' ' * (14 - len(name))}row {r}, col {c}")

    (OUT / "README.md").write_text(
        "# paper_figures\n\n"
        "Hand-drawn-diagram material, generated by "
        "`scripts/make_patch_assets.py`.\n\n"
        f"Source: `{s['name']}`, frame 0, padded from {W}x{H} to "
        f"{img.width}x{img.height} so the {P} px lattice divides it exactly — "
        "which is what the decoder does before it tiles anything.\n\n"
        "| file | what |\n|---|---|\n"
        "| `frame_full.png` | the padded frame, no marks |\n"
        f"| `frame_grid.png` | the same, with the {nh}x{nw} tile lattice |\n"
        "| `frame_grid_marked.png` | the same, with the three example tiles "
        "outlined |\n"
        + "".join(f"| `patch_{k}_{n}.png` | tile at row {r}, col {c} |\n"
                 for k, ((r, c), n) in enumerate(PICKS, 1))
        + "\nColours are converted from the decoder's YCbCr 4:4:4 with "
          "`src.utils.transforms.ycbcr2rgb`; displaying those tensors directly "
          "renders the picture pink.\n")
    print(f"\n  -> {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
